# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 532115d9b53fbaae16db450f7de9e1a3d1b87be5c14ecac69623d3caeb9f44e6c18a48289d8d914ec0e3374b900bc02db9830e8eae35ec8582ad386a1892e3b9

test:
  secret_key_base: 73351d78b77ffd6193405940784d7df1d23454d5268ad7693e80ad6a366c5ebbecfcc527f07ebcd499efff88e81a29d62d8730a73c231201ef6bab7fd0fd57c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
